# Site Settings
title: Jane Doe
url: ''
baseurl: '/simple-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6
# modified slightly
style: style-kz

#Profile information
name: Ayda Doe
tagline: Math major at My College
pic: ayda.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'This is a simple cv website based on Jekyll.'

#sidebar links
email: myemail@gmail.com
phone: 206 123 4567
website: eeholmes.github.io/simple-cv/ #do not add http://
linkedin: 
github: eeholmes
twitter: 
#Update all the sections by editing the files inside _data folder.

# Tracker add google id like UA-xxx here
#analytics: 

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
