# Site Settings
title: Karina Zikan
url: ''
baseurl: '/cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Karina Zikan
tagline: Math/Physics St Olaf College
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am a Math and Physics double major at St Olaf College in Minnesota.  I love mathematics and puzzles.
I enjoy teaching also and have worked as a teacher or instructor at summer schools, theater programs, and skiing programs.
In my free time, I enjoy art, photography and travel.'

#sidebar links
email: karina.zikan@gmail.com
phone: 206 605 8468
website: kzikan.github.io/cv/ #do not add http://
linkedin: 
github: kzikan
twitter: 
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
